#!/usr/bin/env python3
"""Pre-build script: read .env at repo root, generate OmniRecorder/App/DevSecrets.swift.

Called from the "Embed Dev Secrets" pre-build phase in project.yml. The generated
file is gitignored. Runs on every build; if .env is missing or empty, emits nil
values and the app falls back to the Settings UI.
"""
import os
import re

SRCROOT = os.environ.get(
    "SRCROOT",
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
)
ENV_FILE = os.path.join(SRCROOT, ".env")
OUT_FILE = os.path.join(SRCROOT, "OmniRecorder", "App", "DevSecrets.swift")


def parse_env(path):
    values = {}
    if not os.path.exists(path):
        return values
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$", line)
            if not match:
                continue
            key, val = match.group(1), match.group(2).strip()
            if (val.startswith('"') and val.endswith('"')) or \
               (val.startswith("'") and val.endswith("'")):
                val = val[1:-1]
            values[key] = val
    return values


def swift_optional(value):
    if value is None or value == "":
        return "nil"
    escaped = (
        value.replace("\\", "\\\\")
             .replace('"', '\\"')
             .replace("\n", "\\n")
             .replace("\r", "\\r")
    )
    return f'"{escaped}"'


def main():
    env = parse_env(ENV_FILE)
    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w") as f:
        f.write("// Auto-generated by tools/embed-dev-secrets.py. DO NOT EDIT.\n")
        f.write("// Populated from .env at the repo root. Gitignored.\n")
        f.write("enum DevSecrets {\n")
        f.write(
            f"    static let deepgramKey: String? = "
            f"{swift_optional(env.get('DEEPGRAM_KEY'))}\n"
        )
        f.write(
            f"    static let groqKey: String? = "
            f"{swift_optional(env.get('GROQ_KEY'))}\n"
        )
        f.write("}\n")
    print(f"Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
